//! Build script: scan `extensions/*/src/lib.rs` and generate a
//! `register_all` that statically links every extension into the binary.
//!
//! Drop a folder named `extensions/<name>/src/lib.rs` exporting a
//! `pub fn register(reg: &mut pir::plugin::Registry)` and rebuild — the
//! extension's tools are linked in automatically. No Cargo.toml, no
//! runtime loader: just source included at compile time.

use std::fs;
use std::path::Path;

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest);
    let ext_dir = root.join("extensions");

    let mut entries: Vec<String> = Vec::new();
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                entries.push(name);
            }
        }
    }
    entries.sort();

    let mut body = String::new();
    for name in &entries {
        let mod_ident = sanitize(name);
        let abs = ext_dir.join(name).join("src").join("lib.rs");
        let abs = abs.to_string_lossy().into_owned();
        body.push_str(&format!(
            "    #[path = \"{abs}\"]\n    mod ext_{mod_ident};\n    ext_{mod_ident}::register(reg);\n"
        ));
    }

    let out = format!(
        "// Generated by build.rs — do not edit.\n\
         use crate::plugin::Registry;\n\n\
         /// Link every statically compiled extension into `reg`.\n\
         pub fn register_all(reg: &mut Registry) {{\n{body}}}\n"
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("gen_registry.rs");
    fs::write(&dest, out).unwrap();

    // Re-run if any extension source changes; default cargo watches build.rs.
    println!("cargo:rerun-if-changed=extensions");
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                println!("cargo:rerun-if-changed={}", lib.display());
            }
        }
    }
}

/// Turn an arbitrary folder name into a valid Rust identifier fragment.
fn sanitize(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}
