//! Build script: scan `extensions/*/src/lib.rs` and generate a
//! `register_all` that statically links every extension into the binary.
//!
//! Drop a folder named `extensions/<name>/src/lib.rs` exporting a
//! `pub fn register(reg: &mut pir::plugin::Registry)` and rebuild — the
//! extension's tools are linked in automatically. No Cargo.toml, no
//! runtime loader: just source included at compile time.

use std::fs;
use std::path::Path;

/// Paths used in generated `#[path = "..."]` attributes must use `/`
/// separators: on Windows a raw backslash is an invalid Rust string escape
/// (`#[path = "C:\temp\..."]` fails to compile).
fn path_attr(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest);
    let ext_dir = root.join("extensions");

    let mut entries: Vec<String> = Vec::new();
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                entries.push(name);
            }
        }
    }
    entries.sort();

    let mut body = String::new();
    // Registration order matters: the first backend whose `specs()` contain a
    // tool name wins dispatch. We push `prep` first so its enhanced `bash`
    // shadows the builtin `bash`; everything else falls through to `builtin`.
    let mut ordered: Vec<String> = entries.clone();
    ordered.retain(|n| n != "prep");
    let mut final_order = vec!["prep".to_string()];
    final_order.extend(ordered);
    for name in &final_order {
        if !entries.contains(name) {
            continue; // prep not present in this build -> skip
        }
        let mod_ident = sanitize(name);
        let abs = path_attr(&ext_dir.join(name).join("src").join("lib.rs"));
        body.push_str(&format!(
            "    #[path = \"{abs}\"]\n    mod ext_{mod_ident};\n    ext_{mod_ident}::register(reg);\n"
        ));
    }

    // Test module: re-include every extension's `#[cfg(test)] mod tests` into
    // the main binary's test harness so extension unit tests (e.g. the `wt`
    // `startup_report` test) actually run under `cargo test`. Extensions are
    // normally `include!`d inside `register_all`, a *function body*, where Rust
    // does not compile inner `#[cfg(test)]` items — so without this their tests
    // are silently skipped. We re-include them at module scope under cfg(test).
    let mut test_body = String::new();
    for name in &final_order {
        if !entries.contains(name) {
            continue;
        }
        let mod_ident = sanitize(name);
        let abs = path_attr(&ext_dir.join(name).join("src").join("lib.rs"));
        test_body.push_str(&format!(
            "    #[path = \"{abs}\"]\n    mod test_ext_{mod_ident};\n"
        ));
    }
    let out = format!(
        "// Generated by build.rs — do not edit.\n\
         use crate::plugin::Registry;\n\n\
         /// Link every statically compiled extension into `reg`.\n\
         pub fn register_all(reg: &mut Registry) {{\n{body}}}\n\n\
         #[cfg(test)]\n\
         mod ext_tests {{\n\
         {test_body}\
         }}\n"
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("gen_registry.rs");
    fs::write(&dest, out).unwrap();

    // Re-run if any extension source changes; default cargo watches build.rs.
    println!("cargo:rerun-if-changed=extensions");
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                println!("cargo:rerun-if-changed={}", lib.display());
            }
        }
    }
}

/// Turn an arbitrary folder name into a valid Rust identifier fragment.
fn sanitize(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}
