//! Build script: scan `extensions/*/src/lib.rs` and generate a
//! `register_all` that statically links every extension into the binary.
//!
//! Drop a folder named `extensions/<name>/src/lib.rs` exporting a
//! `pub fn register(reg: &mut pir::plugin::Registry)` and rebuild — the
//! extension's tools are linked in automatically. No Cargo.toml, no
//! runtime loader: just source included at compile time.

use std::fs;
use std::path::Path;

/// Paths used in generated `#[path = "..."]` attributes must use `/`
/// separators: on Windows a raw backslash is an invalid Rust string escape
/// (`#[path = "C:\temp\..."]` fails to compile).
fn path_attr(p: &Path) -> String {
    p.to_string_lossy().replace('\\', "/")
}

fn main() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let root = Path::new(&manifest);
    let ext_dir = root.join("extensions");

    // Embed the git commit hash the binary was built from (for the About
    // dialog). Falls back to "unknown" when not in a git checkout.
    let git_hash = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(&manifest)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_string());
    println!("cargo:rustc-env=GIT_HASH={git_hash}");
    println!("cargo:rerun-if-changed=.git/HEAD");

    let mut entries: Vec<String> = Vec::new();
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let name = e.file_name().to_string_lossy().to_string();
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                entries.push(name);
            }
        }
    }
    entries.sort();

    let mut body = String::new();
    // Registration order matters: the first backend whose `specs()` contain a
    // tool name wins dispatch. We push `prep` first so its enhanced `bash`
    // shadows the builtin `bash`; everything else falls through to `builtin`.
    let mut ordered: Vec<String> = entries.clone();
    ordered.retain(|n| n != "prep");
    let mut final_order = vec!["prep".to_string()];
    final_order.extend(ordered);
    for name in &final_order {
        if !entries.contains(name) {
            continue; // prep not present in this build -> skip
        }
        let mod_ident = sanitize(name);
        let abs = path_attr(&ext_dir.join(name).join("src").join("lib.rs"));
        body.push_str(&format!(
            "    #[path = \"{abs}\"]\n    mod ext_{mod_ident};\n    ext_{mod_ident}::register(reg);\n"
        ));
    }

    // Test module: re-include every extension's `#[cfg(test)] mod tests` into
    // the main binary's test harness so extension unit tests (e.g. the `wt`
    // `startup_report` test) actually run under `cargo test`. Extensions are
    // normally `include!`d inside `register_all`, a *function body*, where Rust
    // does not compile inner `#[cfg(test)]` items — so without this their tests
    // are silently skipped. We re-include them at module scope under cfg(test).
    let mut test_body = String::new();
    for name in &final_order {
        if !entries.contains(name) {
            continue;
        }
        let mod_ident = sanitize(name);
        let abs = path_attr(&ext_dir.join(name).join("src").join("lib.rs"));
        test_body.push_str(&format!(
            "    #[path = \"{abs}\"]\n    mod test_ext_{mod_ident};\n"
        ));
    }
    let out = format!(
        "// Generated by build.rs — do not edit.\n\
         // The extension is linked twice on purpose: once as the live tool module\n\
         // (`mod ext_X`) and once as a `#[cfg(test)]` twin (`test_ext_X`) that\n\
         // exercises it as a separate crate — clippy flags that as `duplicate_mod`.\n\
         use crate::plugin::Registry;\n\n\
         /// Link every statically compiled extension into `reg`.\n\
         pub fn register_all(reg: &mut Registry) {{\n{body}}}\n\n\
         #[cfg(test)]\n\
         #[allow(clippy::duplicate_mod)]\n\
         mod ext_tests {{\n\
         {test_body}\
         }}\n"
    );

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("gen_registry.rs");
    fs::write(&dest, out).unwrap();

    // Generate the slash-command completion list from the *actual* dispatch in
    // src/main.rs (the `match cmd` inside `handle_command`). This is the single
    // source of truth: a command you add/remove from the dispatch is
    // automatically added/removed from tab-completion on the next build. No
    // second hand-maintained list to forget to update.
    gen_commands(root, &out_dir);

    // Re-run if the dispatch (the only input to gen_commands) changes.
    println!("cargo:rerun-if-changed=src/main.rs");

    // Re-run if any extension source changes; default cargo watches build.rs.
    println!("cargo:rerun-if-changed=extensions");
    if let Ok(read) = fs::read_dir(&ext_dir) {
        for e in read.flatten() {
            let lib = e.path().join("src").join("lib.rs");
            if lib.is_file() {
                println!("cargo:rerun-if-changed={}", lib.display());
            }
        }
    }
}

/// Turn an arbitrary folder name into a valid Rust identifier fragment.
fn sanitize(name: &str) -> String {
    let mut s: String = name
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect();
    if s.chars().next().map(|c| c.is_ascii_digit()).unwrap_or(false) {
        s.insert(0, '_');
    }
    s
}

/// Generate `gen_commands.rs`: the canonical slash-command list, derived from
/// the *actual* `match cmd` dispatch in `src/main.rs`. The completion and the
/// dispatch are thus guaranteed to stay in sync — you cannot forget to add a
/// command to the completion list, because the completion list is *built from*
/// the dispatch. A command is its own name with a leading `/` (so `/model`
/// matches the `model` arm, `/model*` the `model*` arm, etc.); this is exactly
/// the form the line editor's `Completer` expects.
fn gen_commands(root: &Path, out_dir: &str) {
    let main = root.join("src").join("main.rs");
    let src = fs::read_to_string(&main).unwrap_or_default();
    let cmds = parse_dispatched_commands(&src);
    // De-duplicate but keep first-seen order; some dispatch arms list the same
    // literal twice (e.g. `q` appears in both `quit` and `quarantine`).
    let mut seen = std::collections::HashSet::new();
    let mut uniq: Vec<String> = Vec::new();
    for c in cmds {
        if seen.insert(c.clone()) {
            uniq.push(c);
        }
    }
    // Format as a `&[&str]` literal, one entry per line, matching the style of
    // the hand-written `SLASH_COMMANDS` it replaces. The list is `/`-prefixed
    // (the canonical command name the user types).
    let mut body = String::from("// Generated by build.rs from `match cmd` in src/main.rs — do not edit.\n");
    body.push_str("/// Every slash command the REPL dispatches, derived from the\n");
    body.push_str("/// `match cmd` arms in `handle_command`. Rebuild to regenerate.\n");
    body.push_str("pub const SLASH_COMMANDS: &[&str] = &[\n");
    for c in &uniq {
        body.push_str(&format!("    \"/{c}\",\n"));
    }
    body.push_str("];\n");
    let dest = Path::new(out_dir).join("gen_commands.rs");
    fs::write(&dest, body).unwrap();
}

/// Extract the string literals that are the direct arms of the top-level
/// `match cmd` in `handle_command`. We:
///   1. find `fn handle_command` then the `match cmd {` inside it,
///   2. bracket-match to the matching closing `}`,
///   3. walk that block, collecting string literals at brace-depth 1
///      (i.e. the `match cmd { "x" | "y" => ... }` selector literals).
///
/// Format-string literals like `"{HELP}"` (from blockless `print!` arms) are
/// filtered out so they never pollute the command list.
fn parse_dispatched_commands(src: &str) -> Vec<String> {
    let Some(hc) = src.find("fn handle_command") else {
        return Vec::new();
    };
    let Some(m) = src[hc..].find("match cmd {") else {
        return Vec::new();
    };
    let j = hc + m;
    // Bracket-match from the `{` of `match cmd {`.
    let mut depth = 0usize;
    let mut start: Option<usize> = None;
    let mut end = None;
    let mut k = j;
    while k < src.len() {
        match src.as_bytes()[k] {
            b'{' => {
                depth += 1;
                if start.is_none() {
                    start = Some(k);
                }
            }
            b'}' => {
                depth -= 1;
                if depth == 0 {
                    end = Some(k);
                    break;
                }
            }
            _ => {}
        }
        k += 1;
    }
    let (start, end) = match (start, end) {
        (Some(s), Some(e)) => (s, e),
        _ => return Vec::new(),
    };
    let block = &src[start..=end];

    // Walk the block collecting depth-1 string literals.
    let bytes = block.as_bytes();
    let mut cmds = Vec::new();
    let mut depth = 0i32;
    let mut idx = 0;
    while idx < bytes.len() {
        match bytes[idx] {
            b'{' => depth += 1,
            b'}' => depth -= 1,
            b'"' => {
                // Read to the closing quote (skip escaped quotes).
                let mut s = idx + 1;
                while s < bytes.len() && bytes[s] != b'"' {
                    if bytes[s] == b'\\' {
                        s += 2;
                        continue;
                    }
                    s += 1;
                }
                let lit = &block[idx + 1..s];
                if depth == 1 {
                    // Drop rust format-string literals (`{...}`) — these come
                    // from blockless `print!("{HELP}")` arms, not command names.
                    if !lit.contains('{') {
                        cmds.push(lit.to_string());
                    }
                }
                idx = s + 1;
                continue;
            }
            _ => {}
        }
        idx += 1;
    }
    cmds
}
